### ISSUE TITLE
Collection cannot be created for some channels

### ISSUE THREAD

**Issue by NoodlesStamps** [Alyetama/internetarchive-youtube#4]
I tried to create a Collection but it seems to fail
Other channels are working fine.

```
Current channel: ('NRAJapan', 'https://www.youtube.com/channel/UC5_urTtPY2VjNc1YOI4rBCg')
Traceback (most recent call last):
  File "/usr/local/bin/ia-yt", line 8, in <module>
    sys.exit(cli.main())
  File "/usr/local/lib/python3.10/dist-packages/internetarchive_youtube/cli.py", line 151, in main
    _create_collection(no_logs=args.no_logs)
  File "/usr/local/lib/python3.10/dist-packages/internetarchive_youtube/cli.py", line 63, in _create_collection
    _ = cc.create_collection()
  File "/usr/local/lib/python3.10/dist-packages/internetarchive_youtube/create_collection.py", line 123, in create_collection
    p_last_ten = subprocess.run(shlex.split(cmd_last_ten),
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['yt-dlp', '--playlist-end', '10', '--get-filename', '-o', '{"upload_date": "%(upload_date)s", "title": "%(title)s", "url": "https://www.youtube.com/watch?v=%(id)s", "downloaded": false, "uploaded": false}, ', 'https://www.youtube.com/channel/UC5_urTtPY2VjNc1YOI4rBCg']' returned non-zero exit status 1.


```

**Comment by Alyetama** [comment]
Could you please provide the full command you used?

Based on the details you’ve shared so far, it seems like the issue might be related to the video titles being in Japanese. Have you successfully archived other Japanese channels before? Any additional context or examples of what worked (or didn’t work) could be very helpful.

**Comment by NoodlesStamps** [comment]
Thank you for your prompt reply.
```
pip install internetarchive-youtube
```
```
export  "MONGODB_CONNECTION_STRING=mongodb~~~~etc"
```
```
export "CHANNELS=NRAJapan: https://www.youtube.com/channel/UC5_urTtPY2VjNc1YOI4rBCg"
```
```
ia-yt -C
```
```


Current channel: ('NRAJapan', 'https://www.youtube.com/channel/UC5_urTtPY2VjNc1YOI4rBCg')
Traceback (most recent call last):
  File "/usr/local/bin/ia-yt", line 8, in <module>
    sys.exit(cli.main())
  File "/usr/local/lib/python3.10/dist-packages/internetarchive_youtube/cli.py", line 151, in main
    _create_collection(no_logs=args.no_logs)
  File "/usr/local/lib/python3.10/dist-packages/internetarchive_youtube/cli.py", line 63, in _create_collection
    _ = cc.create_collection()
  File "/usr/local/lib/python3.10/dist-packages/internetarchive_youtube/create_collection.py", line 123, in create_collection
    p_last_ten = subprocess.run(shlex.split(cmd_last_ten),
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['yt-dlp', '--playlist-end', '10', '--get-filename', '-o', '{"upload_date": "%(upload_date)s", "title": "%(title)s", "url": "https://www.youtube.com/watch?v=%(id)s", "downloaded": false, "uploaded": false}, ', 'https://www.youtube.com/channel/UC5_urTtPY2VjNc1YOI4rBCg']' returned non-zero exit status 1.
```

**Comment by NoodlesStamps** [comment]
I tried some channel, and it doesn't work on this channel too.

```
export CHANNELS=PizzaRadio: https://www.youtube.com/channel/UCeWZN7rNRQaHCtMCdHEZFqw
```

**Comment by Alyetama** [comment]
Thank you. I will look into it.

**Comment by NoodlesStamps** [comment]
I appreciate the response, I'll try it out
If it seems too difficult, I'll try that channel another time. Thanks for your help

**Comment by NoodlesStamps** [comment]
I tried again, but unfortunately it didn't work out, so I decided to save it locally using yt-dlp . Thank you for your help, I apologize for the inconvenience.
